### PR TITLE
Avoid AttributeError when calling start_wifi() after stop_bluetooth()

### PR DESCRIPTION
**Pull request by glenrobertson**
`stop_bluetooth()` sets _uart to None, so when calling `start_wifi()`, the call to reset that tries to read self._uart raises a Value Error. Check that _uart is not None

### CODE REVIEW

**Comment by glenrobertson** [comment]
@tekktrik

**Comment by tekktrik** [comment]
Hi, unless there's a specific reason you tagged me, I'll mark this as ready for review and someone will take a look at the earliest opportunity :)

**Comment by glenrobertson** [comment]
@tekktrik thanks! Wasn't sure what the process was and saw you were a committer. Sorry to bother you

**Review by tekktrik — CHANGES_REQUESTED** [review]
Taking a look at this, I think preventing the `AttributeError` is good, but the fix may be slightly more extensive since looking at this now, it seems like this will now just raise the `RuntimeError` if the Bluetooth is off at all.  I think the fix is to also only attempt to check if `startup_message` is empty (and print it if `debug` is true) if `self._uart is not None`.  Was that an issue you experienced with this modified code?

**Comment by glenrobertson** [comment]
@tekktrik thank you for taking an initial look and providing comments.
I updated what I have to only print the startup_message if it is set. I changed it slightly to avoid the negated logic, as I thought it might be more readable.

Since I got back to my project that uses this library, I realized an issue where toggling between bluetooth/wifi a few times, subsequent calls to  `start_bluetooth()` can cause `RuntimeError: Too many adapters`, due to the subsequent calls to the constructor `_bleio.Adapter(.....)`

My use case is that I use bluetooth for pairing so an app can send the wifi credentials, and once they're received, it switches over to wifi to use them. If they are revoked for some reason, I needed to switch back to bluetooth to pair again.

I resolved this in https://github.com/adafruit/Adafruit_CircuitPython_AirLift/pull/8/commits/912f82f6047554f5c8d18e177cdd2fe1e35d052e by avoiding reinitialization of `_bleio_adapter`. I tested it in my own code by using the following to start bluetooth after it had been started and stopped in the past:

```py
if self.esp32._bleio_adapter is None:
    adapter = self.esp32.start_bluetooth()
    _bleio.set_adapter(adapter)
else:
    # avoid "RuntimeError: Too many adapters"
    self.esp32.reset(ESP32.BLUETOOTH)
    self.esp32._busy_cts.switch_to_input()
    self.esp32._gpio0_rts.switch_to_output()
    self.esp32._bleio_adapter.enabled = True
    adapter = self.esp32._bleio_adapter
```

Let me know what you think! Thanks in advance and apologies for the delay in responding.

**Review by FoamyGuy — APPROVED** [review]
I pushed a commit with code format / black changes to make the actions check happy.

This looks good to me now. If I'm following the logic correctly it now checks for existence of the bus or adapter internally rather than always initing a new one and shouldn't try to access a field that doesn't exist yet.

I tested this version successfully with this code intended to try to reproduce the issue described by switching back and forth from bluetooth to wifi and then back.

```py 
import time
import _bleio
from adafruit_airlift.esp32 import ESP32

esp32 = ESP32()
adapter = esp32.start_bluetooth(debug=True)
_bleio.set_adapter(adapter)  # pylint: disable=no-member

print(_bleio.adapter.address)

time.sleep(5)

esp32.stop_bluetooth()
print("bluetooth stopped")

time.sleep(3)

esp32.start_wifi(debug=True)
print("wifi started")

time.sleep(3)

esp32.stop_wifi()
print("wifi stopped")

adapter = esp32.start_bluetooth(debug=True)
_bleio.set_adapter(adapter)  # pylint: disable=no-member

print(_bleio.adapter.address)
```

With the version from this PR the code seems to run and function as intended.

**Comment by glenrobertson** [comment]
@FoamyGuy thank you for helping with this and merging! And thank you @tekktrik for taking a look and providing comments too.

**Pull request merged**
